"use client";

import type { DemoWBSNode } from "@iesl/data";
import type { Schedule } from "../lib/schedule";
import type { Mode } from "@iesl/ui";
import { formatDay } from "../lib/schedule";

export function ExecutiveReport({
  projectName,
  summary,
  tasks,
  schedule,
  mode,
  onClose,
}: {
  projectName: string;
  summary: string;
  tasks: DemoWBSNode[];
  schedule: Schedule;
  mode: Mode;
  onClose: () => void;
}) {
  const sorted = [...tasks].sort((a, b) =>
    a.id.localeCompare(b.id, undefined, { numeric: true }),
  );
  const resources = Array.from(new Set(tasks.map((t) => t.resource).filter(Boolean)));

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center p-4 overflow-auto"
      style={{ background: "rgba(2, 6, 23, 0.85)", backdropFilter: "blur(6px)" }}
    >
      <div className="bg-white text-slate-900 rounded-2xl max-w-4xl w-full my-8 shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between p-6 border-b border-slate-200 bg-gradient-to-r from-blue-600 to-cyan-600 text-white">
          <div>
            <div className="text-xs uppercase tracking-wider opacity-80">Executive Report</div>
            <h2 className="text-2xl font-bold mt-1">IESL Project Plan</h2>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Print / PDF
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Close
            </button>
          </div>
        </div>

        <div className="p-8">
          <div className="mb-8">
            <div className="text-xs uppercase tracking-wider text-slate-500">Project</div>
            <h1 className="text-3xl font-bold mt-1">{projectName}</h1>
            <p className="text-slate-600 mt-2">{summary}</p>
            <div className="mt-4 text-xs text-slate-500 font-mono">
              Generated by ScopeSmith · {mode === "ai" ? "AI Mode (Claude)" : "Demo Mode"} · {new Date().toLocaleDateString("en-GB")}
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 mb-8">
            <Stat label="Total duration" value={`${schedule.totalDays} days`} color="blue" />
            <Stat label="Tasks" value={`${tasks.length}`} color="cyan" />
            <Stat label="Critical path tasks" value={`${schedule.criticalPath.length}`} color="amber" />
          </div>

          <Section title="Executive summary">
            <p className="text-sm text-slate-700">
              The {projectName} campaign spans{" "}
              <strong>{schedule.totalDays} calendar days</strong>, running from{" "}
              {formatDay(0, schedule.startDate)} to {formatDay(schedule.totalDays, schedule.startDate)}.
              The critical path runs through {schedule.criticalPath.length} tasks involving{" "}
              {resources.slice(0, 3).join(", ")}
              {resources.length > 3 ? ` and ${resources.length - 3} more disciplines` : ""}. Schedule
              slippage on any critical-path item pushes project completion one-for-one.
            </p>
          </Section>

          <Section title="Critical path">
            <div className="text-sm text-slate-700">
              {schedule.criticalPath.map((id, i) => {
                const t = schedule.byId[id];
                return (
                  <span key={id}>
                    {i > 0 ? " → " : ""}
                    <span className="font-semibold text-amber-700">{t.name}</span>{" "}
                    <span className="text-xs text-slate-500 font-mono">({t.durationDays}d)</span>
                  </span>
                );
              })}
            </div>
          </Section>

          <Section title="Work Breakdown Structure">
            <table className="w-full text-sm">
              <thead className="text-xs uppercase text-slate-500 border-b border-slate-200">
                <tr>
                  <th className="text-left py-2 font-medium">ID</th>
                  <th className="text-left py-2 font-medium">Task</th>
                  <th className="text-left py-2 font-medium">Resource</th>
                  <th className="text-right py-2 font-medium">Duration</th>
                  <th className="text-right py-2 font-medium">Start</th>
                  <th className="text-right py-2 font-medium">End</th>
                </tr>
              </thead>
              <tbody>
                {sorted.map((t) => {
                  const sch = schedule.byId[t.id];
                  if (!sch) return null;
                  return (
                    <tr key={t.id} className="border-b border-slate-100">
                      <td className="py-1.5 font-mono text-slate-500">{t.id}</td>
                      <td className="py-1.5">
                        {t.critical && <span className="text-amber-600 mr-1">★</span>}
                        {t.name}
                      </td>
                      <td className="py-1.5 text-slate-600">{t.resource ?? "—"}</td>
                      <td className="py-1.5 text-right font-mono">{t.durationDays}d</td>
                      <td className="py-1.5 text-right font-mono text-slate-500">
                        {formatDay(sch.start, schedule.startDate)}
                      </td>
                      <td className="py-1.5 text-right font-mono text-slate-500">
                        {formatDay(sch.end, schedule.startDate)}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </Section>

          <Section title="Resource plan">
            <div className="flex flex-wrap gap-2">
              {resources.map((r) => (
                <span
                  key={r as string}
                  className="px-3 py-1 text-xs rounded-full bg-blue-50 text-blue-700 border border-blue-200"
                >
                  {r}
                </span>
              ))}
            </div>
          </Section>

          <div className="mt-8 pt-6 border-t border-slate-200 text-xs text-slate-400">
            © International Energy Services Limited · This is a workshop demonstration. All data is synthetic.
          </div>
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, color }: { label: string; value: string; color: "blue" | "cyan" | "amber" }) {
  const colors = {
    blue: "bg-blue-50 text-blue-700 border-blue-200",
    cyan: "bg-cyan-50 text-cyan-700 border-cyan-200",
    amber: "bg-amber-50 text-amber-700 border-amber-200",
  } as const;
  return (
    <div className={`p-4 rounded-lg border ${colors[color]}`}>
      <div className="text-xs uppercase tracking-wider opacity-80">{label}</div>
      <div className="text-2xl font-bold mt-1">{value}</div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h3 className="text-sm uppercase tracking-wider text-slate-500 mb-3">{title}</h3>
      {children}
    </div>
  );
}
