"use client";

import type { AiPrediction } from "./RiskLensWorkspace";

export function ExecutiveRiskReport({
  projectName,
  projectSummary,
  ai,
  onClose,
}: {
  projectName: string;
  projectSummary: string;
  ai: AiPrediction;
  onClose: () => void;
}) {
  const sorted = [...ai.newRisks].sort(
    (a, b) => b.likelihood * b.impact - a.likelihood * a.impact,
  );

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center p-4 overflow-auto"
      style={{ background: "rgba(2, 6, 23, 0.85)", backdropFilter: "blur(6px)" }}
    >
      <div className="bg-white text-slate-900 rounded-2xl max-w-4xl w-full my-8 shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between p-6 bg-gradient-to-r from-red-600 to-amber-500 text-white">
          <div>
            <div className="text-xs uppercase tracking-wider opacity-80">Executive Risk Snapshot</div>
            <h2 className="text-2xl font-bold mt-1">{projectName}</h2>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Print / PDF
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Close
            </button>
          </div>
        </div>

        <div className="p-8">
          <div className="mb-6 text-xs text-slate-500 font-mono">
            Generated by RiskLens · Claude · {new Date().toLocaleDateString("en-GB")}
          </div>

          <div className="mb-6">
            <div className="text-xs uppercase tracking-wider text-slate-500 mb-1">Brief</div>
            <p className="text-sm text-slate-700 whitespace-pre-wrap">{projectSummary}</p>
          </div>

          {ai.portfolioInsight && (
            <div className="mb-6 p-4 rounded-lg bg-amber-50 border border-amber-200">
              <div className="text-xs uppercase tracking-wider text-amber-700 mb-1">Portfolio insight</div>
              <p className="text-sm text-slate-800">{ai.portfolioInsight}</p>
            </div>
          )}

          <Section title="Top risks by score">
            <table className="w-full text-sm">
              <thead className="text-xs uppercase text-slate-500 border-b border-slate-200">
                <tr>
                  <th className="text-left py-2 font-medium">Risk</th>
                  <th className="text-left py-2 font-medium">Category</th>
                  <th className="text-right py-2 font-medium">Score</th>
                  <th className="text-right py-2 font-medium">90d Prob.</th>
                </tr>
              </thead>
              <tbody>
                {sorted.map((r, i) => (
                  <tr key={i} className="border-b border-slate-100">
                    <td className="py-1.5">{r.title}</td>
                    <td className="py-1.5 text-slate-600 text-xs">{r.category}</td>
                    <td className="py-1.5 text-right font-mono font-semibold">
                      {r.likelihood * r.impact}
                    </td>
                    <td className="py-1.5 text-right font-mono text-slate-600">
                      {(r.predicted90d * 100).toFixed(0)}%
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Section>

          <Section title="AI-detected risks & mitigations">
            <div className="grid gap-3">
              {ai.newRisks.map((r, i) => (
                <div key={i} className="p-4 rounded-lg border border-slate-200">
                  <div className="flex items-start justify-between gap-3">
                    <div className="font-medium">{r.title}</div>
                    <span className="text-[10px] px-2 py-0.5 rounded bg-amber-100 text-amber-700 shrink-0">
                      {r.category}
                    </span>
                  </div>
                  <div className="text-sm text-slate-600 mt-1">{r.description}</div>
                  <div className="text-sm mt-2">
                    <span className="text-emerald-700 font-medium">Mitigation: </span>
                    {r.mitigation}
                  </div>
                </div>
              ))}
            </div>
          </Section>

          <div className="mt-8 pt-6 border-t border-slate-200 text-xs text-slate-400">
            © International Energy Services Limited.
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h3 className="text-sm uppercase tracking-wider text-slate-500 mb-3">{title}</h3>
      {children}
    </div>
  );
}
