"use client";

import type { HistoricalProject } from "@iesl/data";
import type { Mode } from "@iesl/ui";
import type { Estimate } from "./EstimatorWorkspace";

export function ExecutiveEstimateReport({
  estimate,
  query,
  analogs,
  mode,
  onClose,
}: {
  estimate: Estimate;
  query: string;
  analogs: HistoricalProject[];
  mode: Mode;
  onClose: () => void;
}) {
  const ctgAbs = estimate.costUSDm.likely * (estimate.contingencyPct / 100);
  const approved = estimate.costUSDm.likely + ctgAbs;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center p-4 overflow-auto"
      style={{ background: "rgba(2, 6, 23, 0.85)", backdropFilter: "blur(6px)" }}
    >
      <div className="bg-white text-slate-900 rounded-2xl max-w-4xl w-full my-8 shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between p-6 bg-gradient-to-r from-emerald-600 to-amber-500 text-white">
          <div>
            <div className="text-xs uppercase tracking-wider opacity-80">Estimate Report</div>
            <h2 className="text-2xl font-bold mt-1">{estimate.projectType}</h2>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Print / PDF
            </button>
            <button
              onClick={onClose}
              className="px-4 py-2 text-sm font-medium rounded-lg bg-white/20 hover:bg-white/30"
            >
              Close
            </button>
          </div>
        </div>

        <div className="p-8">
          <div className="mb-6 text-xs text-slate-500 font-mono">
            Generated by EstimatorAI · {mode === "ai" ? "AI Mode (Claude + RAG)" : "Demo Mode"} · {new Date().toLocaleDateString("en-GB")}
          </div>

          <div className="p-4 bg-slate-50 rounded-lg mb-6 border border-slate-200">
            <div className="text-xs uppercase tracking-wider text-slate-500 mb-1">
              Brief
            </div>
            <div className="text-sm">{query}</div>
          </div>

          <div className="grid grid-cols-4 gap-3 mb-6">
            <Stat label="P50 Cost" value={`$${estimate.costUSDm.likely.toFixed(1)}m`} color="emerald" />
            <Stat label="Contingency" value={`${estimate.contingencyPct}%`} color="amber" />
            <Stat label="P80 (approve)" value={`$${approved.toFixed(1)}m`} color="red" />
            <Stat label="Duration (likely)" value={`${estimate.durationMonths.likely} mo`} color="blue" />
          </div>

          <div className="p-4 rounded-lg border-l-4 border-emerald-500 bg-emerald-50 mb-6 text-sm text-slate-800">
            {estimate.narrative}
          </div>

          <Section title="Assumptions">
            <ul className="list-disc pl-5 text-sm space-y-1">
              {estimate.assumptions.map((a, i) => (
                <li key={i}>{a}</li>
              ))}
            </ul>
            <div className="mt-3 text-sm text-slate-600">
              <strong>Contingency rationale:</strong> {estimate.contingencyRationale}
            </div>
          </Section>

          <Section title="Swing factors (USD m vs. P50)">
            <table className="w-full text-sm">
              <thead className="text-xs uppercase text-slate-500 border-b border-slate-200">
                <tr>
                  <th className="text-left py-2 font-medium">Factor</th>
                  <th className="text-right py-2 font-medium">Low</th>
                  <th className="text-right py-2 font-medium">High</th>
                </tr>
              </thead>
              <tbody>
                {estimate.swingFactors.map((s) => (
                  <tr key={s.label} className="border-b border-slate-100">
                    <td className="py-1.5">{s.label}</td>
                    <td className="py-1.5 text-right font-mono text-emerald-700">
                      {s.lowUSDm.toFixed(1)}
                    </td>
                    <td className="py-1.5 text-right font-mono text-red-700">
                      +{s.highUSDm.toFixed(1)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Section>

          <Section title="Analog projects referenced">
            <table className="w-full text-sm">
              <thead className="text-xs uppercase text-slate-500 border-b border-slate-200">
                <tr>
                  <th className="text-left py-2 font-medium">Project</th>
                  <th className="text-left py-2 font-medium">Year</th>
                  <th className="text-right py-2 font-medium">Budget</th>
                  <th className="text-right py-2 font-medium">Actual</th>
                  <th className="text-left py-2 font-medium">Outcome</th>
                </tr>
              </thead>
              <tbody>
                {analogs.map((a) => (
                  <tr key={a.id} className="border-b border-slate-100">
                    <td className="py-1.5">{a.name}</td>
                    <td className="py-1.5 font-mono text-slate-500">{a.yearCompleted}</td>
                    <td className="py-1.5 text-right font-mono">${a.budgetUSDm.toFixed(1)}m</td>
                    <td className="py-1.5 text-right font-mono">${a.actualUSDm.toFixed(1)}m</td>
                    <td className="py-1.5 text-xs text-slate-600">{a.outcome}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </Section>

          <div className="mt-8 pt-6 border-t border-slate-200 text-xs text-slate-400">
            © International Energy Services Limited · Workshop demonstration · Synthetic data
          </div>
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, color }: { label: string; value: string; color: "emerald" | "amber" | "red" | "blue" }) {
  const colors = {
    emerald: "bg-emerald-50 text-emerald-700 border-emerald-200",
    amber: "bg-amber-50 text-amber-700 border-amber-200",
    red: "bg-red-50 text-red-700 border-red-200",
    blue: "bg-blue-50 text-blue-700 border-blue-200",
  } as const;
  return (
    <div className={`p-4 rounded-lg border ${colors[color]}`}>
      <div className="text-xs uppercase tracking-wider opacity-80">{label}</div>
      <div className="text-2xl font-bold mt-1">{value}</div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h3 className="text-sm uppercase tracking-wider text-slate-500 mb-3">{title}</h3>
      {children}
    </div>
  );
}
